[트리] - 11월 22일
Altu-Bitu/Altu-Bitu-Chaerin pull request #17
Opened 2021-11-21 20:09 UTC by zolio

필수 1문제, 선택 2문제 풀이했습니다.
남은 문제는 추가제출하도록 하겠습니다.

2021-11-22 08:35 UTC, bsa0322 requested changes
p1. 잘 풀어주셨네요!! 조금 더 리팩토링할 수 있는 부분이 보이네요. p1이 붙은 부분은 꼭 수정해주세요! 수정 후, 저 다시 리뷰어로 호출해주세요. 제가 드린 코멘트가 애매하다 싶어도 언제든지 불러주세요! 수고하셨습니다~!

2021-11-22 08:35 UTC, bsa0322 commented on 11월 16일 - 트리/14503.cpp
> +}
p2. 방향 관리는 지금처럼 함수를 만드는 것보다 방향의 변화값을 배열로 만들어서 관리하는 게 좋아요! 방향 배열은 특히 BFS, DFS를 풀 때 많이 사용했어요! 
방향 배열을 만든 후, 회전은 배열의 인덱스를 통해 관리할 수 있어요.

2021-11-22 08:35 UTC, bsa0322 commented on 11월 16일 - 트리/14503.cpp
> +    }
p1. 우선 이 부분은 함수화를 하는 게 좋아요! 그럼 goto 문 사용 없이 바로 답을 반환할 수 있겠네요!
더불어 break;문 대신 다른 명령어를 사용하면, while문 지금처럼 중첩으로 사용하지 않고, 하나로 사용할 수 있어요!

2021-11-22 08:35 UTC, bsa0322 commented on 11월 16일 - 트리/14675.cpp
> +        if (t == 2) cout << "yes\n";
p2. 정의를 잘 파악하셨네요!! 짧지만 이 부분은 정답을 리턴하도록 함수화를 해도 괜찮겠네요!

2021-11-22 08:35 UTC, bsa0322 commented on 11월 16일 - 트리/15681.cpp
> +}
p2. void형 함수는 피해주는 게 좋아요! 이 함수는, 정답을 바로 리턴해주는 int 리턴형 함수로 만들어주면 좋아요! 
더불어 지금처럼 트리를 만들어 준 후, 검사해주시는 것도 너무 좋지만, 코드를 줄이고 싶으시다면 양방향 그래프를 트리로 만드는 원리를 그대로 여기서 적용해서 함수 하나로 처리할 수 있어요!

2021-11-24 04:00 UTC, Yuna9949 commented
2011 5639 추가제출확인되셨습니다. 다음부터는 추가 제출은 따로 PR 생성해서 제출해주세요.

2021-11-24 04:35 UTC, bsa0322 approved these changes

2021-11-29 10:31 UTC, merged